export interface NigerianState {
  name: string;
  slug: string;
  path: string;
}

export const nigerianStates: NigerianState[] = [
  { name: "Abia State", slug: "abia", path: "/state/abia" },
  { name: "Adamawa State", slug: "adamawa", path: "/state/adamawa" },
  { name: "Akwa Ibom State", slug: "akwa-ibom", path: "/state/akwa-ibom" },
  { name: "Anambra State", slug: "anambra", path: "/state/anambra" },
  { name: "Bauchi State", slug: "bauchi", path: "/state/bauchi" },
  { name: "Bayelsa State", slug: "bayelsa", path: "/state/bayelsa" },
  { name: "Benue State", slug: "benue", path: "/state/benue" },
  { name: "Borno State", slug: "borno", path: "/state/borno" },
  { name: "Cross River State", slug: "cross-river", path: "/state/cross-river" },
  { name: "Delta State", slug: "delta", path: "/state/delta" },
  { name: "Ebonyi State", slug: "ebonyi", path: "/state/ebonyi" },
  { name: "Edo State", slug: "edo", path: "/state/edo" },
  { name: "Ekiti State", slug: "ekiti", path: "/state/ekiti" },
  { name: "Enugu State", slug: "enugu", path: "/state/enugu" },
  { name: "Federal Capital Territory", slug: "fct", path: "/state/fct" },
  { name: "Gombe State", slug: "gombe", path: "/state/gombe" },
  { name: "Imo State", slug: "imo", path: "/state/imo" },
  { name: "Jigawa State", slug: "jigawa", path: "/state/jigawa" },
  { name: "Kaduna State", slug: "kaduna", path: "/state/kaduna" },
  { name: "Kano State", slug: "kano", path: "/state/kano" },
  { name: "Katsina State", slug: "katsina", path: "/state/katsina" },
  { name: "Kebbi State", slug: "kebbi", path: "/state/kebbi" },
  { name: "Kogi State", slug: "kogi", path: "/state/kogi" },
  { name: "Kwara State", slug: "kwara", path: "/state/kwara" },
  { name: "Lagos State", slug: "lagos", path: "/state/lagos" },
  { name: "Nasarawa State", slug: "nasarawa", path: "/state/nasarawa" },
  { name: "Niger State", slug: "niger", path: "/state/niger" },
  { name: "Ogun State", slug: "ogun", path: "/state/ogun" },
  { name: "Ondo State", slug: "ondo", path: "/state/ondo" },
  { name: "Osun State", slug: "osun", path: "/state/osun" },
  { name: "Oyo State", slug: "oyo", path: "/state/oyo" },
  { name: "Plateau State", slug: "plateau", path: "/state/plateau" },
  { name: "Rivers State", slug: "rivers", path: "/state/rivers" },
  { name: "Sokoto State", slug: "sokoto", path: "/state/sokoto" },
  { name: "Taraba State", slug: "taraba", path: "/state/taraba" },
  { name: "Yobe State", slug: "yobe", path: "/state/yobe" },
  { name: "Zamfara State", slug: "zamfara", path: "/state/zamfara" },
];
