export interface NigerianState {
  name: string;
  slug: string;
  path: string;
}

export const nigerianStates: NigerianState[] = [
  { name: "Abia State", slug: "abia", path: "https://abia.lgpoa.ng" },
  { name: "Adamawa State", slug: "adamawa", path: "https://adamawa.lgpoa.ng" },
  { name: "Akwa Ibom State", slug: "akwa-ibom", path: "https://akwaibom.lgpoa.ng" },
  { name: "Anambra State", slug: "anambra", path: "https://anambra.lgpoa.ng" },
  { name: "Bauchi State", slug: "bauchi", path: "https://bauchi.lgpoa.ng" },
  { name: "Bayelsa State", slug: "bayelsa", path: "https://bayelsa.lgpoa.ng" },
  { name: "Benue State", slug: "benue", path: "https://benue.lgpoa.ng" },
  { name: "Borno State", slug: "borno", path: "https://borno.lgpoa.ng" },
  { name: "Cross River State", slug: "cross-river", path: "https://crossriver.lgpoa.ng" },
  { name: "Delta State", slug: "delta", path: "https://delta.lgpoa.ng" },
  { name: "Ebonyi State", slug: "ebonyi", path: "https://ebonyi.lgpoa.ng" },
  { name: "Edo State", slug: "edo", path: "https://edo.lgpoa.ng" },
  { name: "Ekiti State", slug: "ekiti", path: "https://ekiti.lgpoa.ng" },
  { name: "Enugu State", slug: "enugu", path: "https://enugu.lgpoa.ng" },
  { name: "Federal Capital Territory", slug: "fct", path: "https://fct.lgpoa.ng" },
  { name: "Gombe State", slug: "gombe", path: "https://gombe.lgpoa.ng" },
  { name: "Imo State", slug: "imo", path: "https://imo.lgpoa.ng" },
  { name: "Jigawa State", slug: "jigawa", path: "https://jigawa.lgpoa.ng" },
  { name: "Kaduna State", slug: "kaduna", path: "https://kaduna.lgpoa.ng" },
  { name: "Kano State", slug: "kano", path: "https://kano.lgpoa.ng" },
  { name: "Katsina State", slug: "katsina", path: "https://katsina.lgpoa.ng" },
  { name: "Kebbi State", slug: "kebbi", path: "https://kebbi.lgpoa.ng" },
  { name: "Kogi State", slug: "kogi", path: "https://kogi.lgpoa.ng" },
  { name: "Kwara State", slug: "kwara", path: "https://kwara.lgpoa.ng" },
  { name: "Lagos State", slug: "lagos", path: "https://lagos.lgpoa.ng" },
  { name: "Nasarawa State", slug: "nasarawa", path: "https://nasarawa.lgpoa.ng" },
  { name: "Niger State", slug: "niger", path: "https://niger.lgpoa.ng" },
  { name: "Ogun State", slug: "ogun", path: "https://ogun.lgpoa.ng" },
  { name: "Ondo State", slug: "ondo", path: "https://ondo.lgpoa.ng" },
  { name: "Osun State", slug: "osun", path: "https://osun.lgpoa.ng" },
  { name: "Oyo State", slug: "oyo", path: "https://oyo.lgpoa.ng" },
  { name: "Plateau State", slug: "plateau", path: "https://plateau.lgpoa.ng" },
  { name: "Rivers State", slug: "rivers", path: "https://rivers.lgpoa.ng" },
  { name: "Sokoto State", slug: "sokoto", path: "https://sokoto.lgpoa.ng" },
  { name: "Taraba State", slug: "taraba", path: "https://taraba.lgpoa.ng" },
  { name: "Yobe State", slug: "yobe", path: "https://yobe.lgpoa.ng" },
  { name: "Zamfara State", slug: "zamfara", path: "https://zamfara.lgpoa.ng" },
];
